Repository MrucznikRolePlay/Mrucznik-RP-gamemode, pull requests merged in 2024-02, with the labels that each got.

#370 Usunięcie transferu podatku z kasyna do sejfu 19
  gamemodes/system/funkcje.pwn
Labels: Enhancement, Economy

#409 Ograniczenie /wezportfel
  gamemodes/commands/cmd/wezportfel.pwn
Labels: Enhancement

#388 fix sejfy za areszt i mandat
  gamemodes/commands/cmd/aresztuj.pwn
  gamemodes/modules/oferty/commands/akceptuj/akceptuj_impl.pwn
Labels: Bugfix, Economy

#382 fix /pr spawn
  gamemodes/commands/cmd/pr.pwn
  gamemodes/system/funkcje.pwn
Labels: Bugfix

#375 Poprawki do ryb
  db/mrp_samp.sql
  gamemodes/commands/cmd/licencje.pwn
  gamemodes/modules/fishing/commands/lowienie/lowienie_impl.pwn
  gamemodes/modules/fishing/fishing.pwn
  gamemodes/mysql/mru_mysql.pwn
  gamemodes/system/funkcje.pwn
  gamemodes/system/timery.pwn
Labels: New Functionality

#374 Dodanie prostej, usuniętej komendy /paralizator
  gamemodes/commands/cmd/paralizator.pwn
  gamemodes/commands/commands.pwn
Labels: New Functionality

#404 Poprawki do systemu zabezpieczeń, poprawki @cmd
  gamemodes/Mrucznik-RP.pwn
  gamemodes/commands/cmd/rozwiaz.pwn
  gamemodes/commands/cmd/zablokujw.pwn
  gamemodes/modules/weryfikacje/weryfikacje.pwn
  pawn.json
Labels: New Functionality

#419 Na prośbę Leppere zmiana linków do Lepa Station
  .gitmodules
  README.md
  amx_fix.sh
  db/mrp_samp.sql
  gamemodes/commands/cmd/wezzlecenie.pwn
  gamemodes/dialogs/OnDialogResponse.pwn
  pawn.json
Labels: Enhancement

#415 Antyczit na kłębienie pojazdów - usprawnienie
  gamemodes/modules/antycheat/antycheat.pwn
  gamemodes/system/funkcje.pwn
Labels: Enhancement, Bugfix

#430 Złodziej aut - poprawki i naprawy błędów (dodatkowo, z konieczności - naprawa /icons)
  gamemodes/Mrucznik-RP.pwn
  gamemodes/commands/cmd/deletedom.pwn
  gamemodes/commands/cmd/icons.pwn
  gamemodes/modules/zlodziej_aut/zlodziej_aut.hwn
  gamemodes/modules/zlodziej_aut/zlodziej_aut.pwn
  gamemodes/modules/zlodziej_aut/zlodziej_aut_timers.pwn
  gamemodes/system/funkcje.pwn
  gamemodes/system/zmienne.pwn
Labels: Enhancement

#426 Sprzedawanie zestawu akceptowane komendą /sprzedajzestaw
  gamemodes/commands/cmd/sprzedajzestaw.pwn
  gamemodes/dialogs/OnDialogResponse.pwn
  gamemodes/modules/oferty/commands/akceptuj/akceptuj_impl.pwn
  gamemodes/system/definicje.pwn
  gamemodes/system/zmienne.pwn
Labels: Enhancement, Bugfix

#429 Sejfy mats dla organizacji
  db/mrp_samp.sql
  gamemodes/commands/cmd/sejfrodzina.pwn
  gamemodes/dialogs/OnDialogResponse.pwn
  gamemodes/system/funkcje.pwn
  gamemodes/system/zmienne.pwn
Labels: New Functionality, Economy
